name: Markdownlint (PR files)

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.md"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.2
        with:
          files: |
            **/*.md

      - name: Copy upstream dependencies
        run: |
          curl -L https://raw.githubusercontent.com/mdn/content/main/package.json > package.json
          curl -L https://raw.githubusercontent.com/mdn/content/main/yarn.lock > yarn.lock

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install all yarn packages
        run: |
          yarn --frozen-lockfile

      - name: Lint markdown files
        run: |
          echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
          yarn markdownlint ${{ steps.changed-files.outputs.all_changed_files }}
